///////////////////////////////////////////////////////////
//  BaseVoltage.cs
//  Implementation of the Class BaseVoltage
//  Generated by Enterprise Architect
//  Created on:      21-Sep-2016 12:14:08 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Core;
namespace CIM.IEC61970.Base.Core {
    /// <summary>
    /// Defines a system base voltage which is referenced.
    /// </summary>
    /// 
    [Serializable]
    public class BaseVoltage : IdentifiedObject {

		/// <summary>
		/// The power system resource's base voltage.
		/// </summary>
		public float nominalVoltage
        {
            get;
            set;
        }
		/// <summary>
		/// All conducting equipment with this base voltage.  Use only when there is no
		/// voltage level container used and only one base voltage applies.  For example,
		/// not used for transformers.
		/// </summary>
		public System.Collections.Generic.List<ConductingEquipment> ConductingEquipment =  new List<Core.ConductingEquipment>();

		public BaseVoltage(){

		}

		~BaseVoltage(){

		}

	}//end BaseVoltage

}//end namespace Core