///////////////////////////////////////////////////////////
//  ConductingEquipment.cs
//  Implementation of the Class ConductingEquipment
//  Generated by Enterprise Architect
//  Created on:      21-Sep-2016 12:14:09 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Core;
using System.Xml.Serialization;

namespace CIM.IEC61970.Base.Core {
    /// <summary>
    /// The parts of the AC power system that are designed to carry current or that are
    /// conductively connected through terminals.
    /// </summary>
    /// 
    [XmlInclude(typeof(Terminal))]
    public class ConductingEquipment : Equipment {
        public List<Terminal> terminali;
        public ConductingEquipment(){
            terminali = new List<Terminal>();
        }

		~ConductingEquipment(){

		}

	}//end ConductingEquipment

}//end namespace Core