///////////////////////////////////////////////////////////
//  ConnectivityNodeContainer.cs
//  Implementation of the Class ConnectivityNodeContainer
//  Generated by Enterprise Architect
//  Created on:      21-Sep-2016 12:14:09 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Core;
namespace CIM.IEC61970.Base.Core {
    /// <summary>
    /// A base class for all objects that may contain connectivity nodes or topological
    /// nodes.
    /// </summary>
    /// 
    [Serializable]
    public class ConnectivityNodeContainer : PowerSystemResource {
        public List<ConnectivityNode> connectivityNodes = new List<ConnectivityNode>();
        public ConnectivityNodeContainer(){
          
        }

		~ConnectivityNodeContainer(){

		}

	}//end ConnectivityNodeContainer

}//end namespace Core