///////////////////////////////////////////////////////////
//  EquipmentContainer.cs
//  Implementation of the Class EquipmentContainer
//  Generated by Enterprise Architect
//  Created on:      21-Sep-2016 12:14:10 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Core;
namespace CIM.IEC61970.Base.Core {
	/// <summary>
	/// A modeling construct to provide a root class for containing equipment.
	/// </summary>
	public class EquipmentContainer : ConnectivityNodeContainer {

		/// <summary>
		/// Contained equipment.
		/// </summary>
		public List<Equipment> Equipments;

		public EquipmentContainer(){
            Equipments = new List<Equipment>();
        }

		~EquipmentContainer(){

		}

	}//end EquipmentContainer

}//end namespace Core