///////////////////////////////////////////////////////////
//  Substation.cs
//  Implementation of the Class Substation
//  Generated by Enterprise Architect
//  Created on:      21-Sep-2016 12:14:11 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Core;
using Milica_Tiodorovic_e3582013_rva;

namespace CIM.IEC61970.Base.Core {
	/// <summary>
	/// A collection of equipment for purposes other than generation or utilization,
	/// through which electric energy in bulk is passed for the purposes of switching
	/// or modifying its characteristics.
	/// </summary>
    /// 
    
	public class Substation : EquipmentContainer, IPrototype {
        public double x { get; set; }
        public double y { get; set; }
        /// <summary>
        /// The voltage levels within this substation.
        /// </summary>
        public System.Collections.Generic.List<VoltageLevel> VoltageLevels;
		/// <summary>
		/// Bays contained in the substation.
		/// </summary>
		public System.Collections.Generic.List<Bay> Bays;

       

        public Substation(){
            VoltageLevels = new List<VoltageLevel>();
            Bays = new List<Bay>();
        }

		~Substation(){

		}
       

        public object Clone()
        {
            Substation s = new Substation();

            s.aliasName = this.aliasName;
            s.description = "clone_" + this.mRID;
            s.name = this.name;
            s.connectivityNodes = new List<ConnectivityNode>();
            s.Bays = new List<Bay>(this.Bays);
            s.Equipments = new List<Equipment>(this.Equipments);
            s.VoltageLevels = new List<VoltageLevel>(this.VoltageLevels);
            s.x = -1;
            s.y = -1;


           
            return s;
        }

        public override string ToString()
        {
            return "id: " + mRID + ", name: " + name;
        }
    }//end Substation

}//end namespace Core