///////////////////////////////////////////////////////////
//  AsynchronousMachineKind.cs
//  Implementation of the Enumeration AsynchronousMachineKind
//  Generated by Enterprise Architect
//  Created on:      21-Sep-2016 12:15:11 PM
//  Original author: msphuku2
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace CIM.IEC61970.Base.Wires {
	/// <summary>
	/// Kind of Asynchronous Machine.
	/// </summary>
	public enum AsynchronousMachineKind : int {

		/// <summary>
		/// The Asynchronous Machine is a generator.
		/// </summary>
		generator,
		/// <summary>
		/// The Asynchronous Machine is a motor.
		/// </summary>
		motor

	}//end AsynchronousMachineKind

}//end namespace Wires