///////////////////////////////////////////////////////////
//  Ground.cs
//  Implementation of the Class Ground
//  Generated by Enterprise Architect
//  Created on:      21-Sep-2016 12:15:12 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Core;
namespace CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A point where the system is grounded used for connecting conducting equipment
	/// to ground. The power system model can have any number of grounds.
	/// </summary>
	public class Ground : ConductingEquipment {


        public string trafoId
        {
            get;
            set;
        }
		public Ground(){

		}

		~Ground(){

		}

	}//end Ground

}//end namespace Wires