///////////////////////////////////////////////////////////
//  LoadBreakSwitch.cs
//  Implementation of the Class LoadBreakSwitch
//  Generated by Enterprise Architect
//  Created on:      21-Sep-2016 12:15:13 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Wires;
namespace CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A mechanical switching device capable of making, carrying, and breaking
	/// currents under normal operating conditions.
	/// </summary>
	public class LoadBreakSwitch : ProtectedSwitch {


        public string trafoId
        {
            get;
            set;
        }
        public LoadBreakSwitch(){

		}

		~LoadBreakSwitch(){

		}

	}//end LoadBreakSwitch

}//end namespace Wires