///////////////////////////////////////////////////////////
//  SynchronousMachine.cs
//  Implementation of the Class SynchronousMachine
//  Generated by Enterprise Architect
//  Created on:      21-Sep-2016 12:15:14 PM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Wires;
namespace CIM.IEC61970.Base.Wires {
	/// <summary>
	/// An electromechanical device that operates with shaft rotating synchronously
	/// with the network. It is a single machine operating either as a generator or
	/// synchronous condenser or pump.
	/// </summary>
	public class SynchronousMachine : RotatingMachine {

        /// <summary>
        /// Default base reactive power value. This value represents the initial reactive
        /// power that can be used by any application function.
        /// </summary>
        /// 

        public string trafoId
        {
            get;
            set;
        }
        public float baseQ
        {
            get;
            set;
        }
		/// <summary>
		/// Maximum reactive power limit. This is the maximum (nameplate) limit for the
		/// unit.
		/// </summary>
		public float maxQ
        {
            get;
            set;
        }
		/// <summary>
		/// Maximum voltage limit for the unit.
		/// </summary>
		public float maxU
        {
            get;
            set;
        }
		/// <summary>
		/// Minimum reactive power limit for the unit.
		/// </summary>
		public float minQ
        {
            get;
            set;
        }
		/// <summary>
		/// Minimum voltage  limit for the unit.
		/// </summary>
		public float minU
        {
            get;
            set;
        }
		/// <summary>
		/// Current mode of operation.
		/// </summary>
		public SynchronousMachineOperatingMode operatingMode
        {
            get;
            set;
        }
		/// <summary>
		/// Modes that this synchronous machine can operate in.
		/// </summary>
		public SynchronousMachineKind type
        {
            get;
            set;
        }
		/// <summary>
		/// Range of generator voltage regulation (PG in the IEC 60909-0) used for
		/// calculation of the impedance correction factor KG defined in IEC 60909-0
		/// This attribute is used to describe the operating voltage of the generating unit.
		/// 
		/// </summary>
		public float voltageRegulationRange
        {
            get;
            set;
        }

		public SynchronousMachine(){

		}

		~SynchronousMachine(){

		}

	}//end SynchronousMachine

}//end namespace Wires